"""
Regenerates docs/data-model.md from the Pydantic models in
civic_scraper.models and fails if the committed file doesn't match.

Field-level facts (name, type, required/optional, description) are the
part of data-model.md that actually goes stale the moment a model
changes - adding a field, renaming one, widening a Literal. Those facts
are generated here directly from model_fields/model_computed_fields
introspection, never hand-typed. The section grouping and per-model
framing sentences are hand-authored in this script's templates, the same
way scripts/build_gold_set.py and scripts/build_style_cases.py are
hand-authored generators for their own artifacts - "generated" means
"the source of truth is code that produces it deterministically," not
"nobody wrote any of the words."

    uv run python checks/docs_drift.py           # check mode (CI): exit 1 on drift
    uv run python checks/docs_drift.py --write    # regenerate docs/data-model.md

Descriptions come from each field's Field(description=...) - see
models.py's module docstring for why that's also where the tool schema
Claude extracts against gets its own field descriptions from. A field
with no description renders with an empty Notes cell rather than
failing, so adding a field without a description doesn't crash CI - it
just produces a visibly thin doc row, which is its own honest signal.
"""

import sys
import types
import typing
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "services" / "workers"))

from civic_scraper import models  # noqa: E402

_REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = _REPO_ROOT / "docs" / "data-model.md"

_UNION_ORIGINS = {typing.Union, getattr(types, "UnionType", object())}


def render_type(annotation) -> str:
    """Render a type annotation the way this doc has always shown types -
    "str | None", "list[Extracted[Motion]]", 'Literal["a", "b"]' - rather
    than Python's fully-qualified typing repr."""
    if annotation is type(None):
        return "None"

    origin = typing.get_origin(annotation)
    if origin is None:
        return getattr(annotation, "__name__", str(annotation))

    args = typing.get_args(annotation)
    if origin is typing.Literal:
        rendered = [f'"{a}"' if isinstance(a, str) else repr(a) for a in args]
        return f"Literal[{', '.join(rendered)}]"
    if origin in _UNION_ORIGINS:
        return " | ".join(render_type(a) for a in args)

    origin_name = getattr(origin, "__name__", str(origin))
    return f"{origin_name}[{', '.join(render_type(a) for a in args)}]"


def render_field_table(model: type) -> str:
    rows = ["| Field | Type | Notes |", "|---|---|---|"]
    for name, field in model.model_fields.items():
        note = (field.description or "").replace("\n", " ")
        rows.append(f"| `{name}` | `{render_type(field.annotation)}` | {note} |")
    for name, computed in getattr(model, "model_computed_fields", {}).items():
        note = (computed.description or "").replace("\n", " ")
        rows.append(f"| `{name}` (computed) | `{render_type(computed.return_type)}` | {note} |")
    return "\n".join(rows)


def _section(title: str, models_and_intros: list[tuple[type, str]]) -> str:
    parts = [f"## {title}", ""]
    for model, intro in models_and_intros:
        parts.append(f"### {model.__name__}")
        parts.append("")
        if intro:
            parts.append(intro)
            parts.append("")
        parts.append(render_field_table(model))
        parts.append("")
    return "\n".join(parts)


def generate() -> str:
    """The full contents of docs/data-model.md. Section grouping and
    per-model intro sentences are authored here; every field row comes
    from live introspection of civic_scraper.models."""
    header = """<!-- GENERATED by checks/docs_drift.py - do not hand-edit.
     Run `uv run python checks/docs_drift.py --write` to regenerate. -->

# Data Model

Every model here is a Pydantic `BaseModel` defined in
[`services/workers/civic_scraper/models.py`](../services/workers/civic_scraper/models.py).
Unlike the dataclasses this replaced, these validate at construction —
required fields reject `None`, `Literal` fields reject unknown values.
That's deliberate: a connector or extraction step that produces
malformed data should fail loudly at the point it's constructed, not
downstream when something tries to use it.

This file is generated (`checks/docs_drift.py`), not hand-maintained —
every field, type, and note below comes straight from each model's own
`Field(description=...)`, so it cannot silently drift from the code the
way hand-copied documentation can. CI fails if this file doesn't match
what `checks/docs_drift.py` produces right now.

Two families of model live in this one file, and the split matters:

- **Scrape output** — `Meeting`, `Attachment`, `LegislationDetails`,
  `LegistarAgendaEntry`. What a connector reads directly off a
  platform's own HTML. No inference, no LLM involved.
- **Extraction output** — `Provenance`, `Extracted[T]`, `Person`,
  `VoteRecord`, `Motion`, `Location`, `MonetaryAmount`, `AgendaItem`.
  What the LLM extraction layer (`extraction/agenda_item.py`) produces
  from a fetched document. See
  [Why two "agenda item" models](#why-two-agenda-item-models) below for
  why `AgendaItem` and `LegistarAgendaEntry` are deliberately not the
  same type, and
  [`docs/engineering-log.md`](engineering-log.md) for the fuller story
  of how that decision was made.
"""

    scrape_output = _section(
        "Scrape output",
        [
            (
                models.Meeting,
                "One row in a platform's meeting calendar, normalized. Output of "
                "`CivicConnector.list_meetings()`.",
            ),
            (
                models.Attachment,
                "A single supporting document linked from a `LegislationDetails` page.",
            ),
            (
                models.LegislationDetails,
                "The expanded record behind a single `LegistarAgendaEntry.legislation_url`, "
                "fetched by `LegistarConnector.get_legislation_details()`.",
            ),
            (
                models.LegistarAgendaEntry,
                "One row of Legistar's own agenda-item listing, scraped directly from a "
                "meeting-detail page via `LegistarConnector.get_meeting_details()`. This is "
                "**not** the extraction-layer `AgendaItem` below — see "
                '[Why two "agenda item" models](#why-two-agenda-item-models).',
            ),
        ],
    )

    extraction_output = _section(
        "Extraction output",
        [
            (
                models.Provenance,
                "Where an extracted value came from, so it can be checked against the "
                "source document rather than trusted blindly.",
            ),
            (
                models.Extracted,
                "A generic wrapper — every extracted value, whatever its type, carries a "
                "confidence score and provenance alongside it. There is no path to "
                "constructing an extracted fact without both. (`value`'s type renders as "
                "`T` here since this table reflects the generic itself, not one of its "
                "concrete instantiations like `Extracted[Motion]`.)",
            ),
            (models.Person, ""),
            (models.VoteRecord, ""),
            (models.Motion, ""),
            (models.Location, ""),
            (models.MonetaryAmount, ""),
            (
                models.AgendaItem,
                "The extraction-layer record for one agenda item — everything an LLM "
                "pass over a fetched document is meant to produce. See "
                '[Why two "agenda item" models](#why-two-agenda-item-models).',
            ),
        ],
    )

    why_two_models = """### Why two "agenda item" models

`LegistarAgendaEntry` and `AgendaItem` look like they should be the same
thing, and almost were — but they answer different questions.
`LegistarAgendaEntry` is "what did Legistar's own HTML table say about
this row" (File #, a type label, an action/result Legistar already
recorded). `AgendaItem` is "what did an LLM pass over the actual agenda
document conclude" (motions, named people, locations, dollar amounts,
each individually confidence-scored and provenance-checked). The first
is free — a byproduct of scraping a platform that happens to expose
structured HTML. The second requires document fetch and an LLM call.
Naming them the same thing would have made "does this `Meeting` have
real extraction output or just a scraped listing" a question you could
only answer by inspecting field values instead of the type. Full
history of this decision: [`docs/engineering-log.md`](engineering-log.md).
"""

    document_fetch_output = _section(
        "Document fetch output",
        [
            (
                models.FetchedDocument,
                "Output of `fetch_and_extract()` in "
                "[`document_text.py`](../services/workers/civic_scraper/document_text.py) — "
                "a cached local copy of a fetched agenda/minutes document plus its extracted text.",
            ),
        ],
    )

    design_principle = """## Design principle: flexible parsing, standardized output

Different cities on the same platform expose different columns.
Connectors absorb that variance internally (see
[`architecture.md`](architecture.md#connector-framework)) and always
return the same scrape-output models. If a piece of data isn't
available from a given source, the field is `None` — connectors never
invent placeholder values, and never add platform-specific fields to
the shared model.
"""

    return "\n".join(
        [
            header,
            scrape_output,
            extraction_output,
            why_two_models,
            document_fetch_output,
            design_principle,
        ]
    )


def main() -> int:
    generated = generate()

    if "--write" in sys.argv:
        OUTPUT_PATH.write_text(generated, encoding="utf-8")
        print(f"Wrote {OUTPUT_PATH}")
        return 0

    if not OUTPUT_PATH.exists():
        print(f"{OUTPUT_PATH} does not exist. Run with --write to create it.")
        return 1

    committed = OUTPUT_PATH.read_text(encoding="utf-8")
    if committed == generated:
        print(f"{OUTPUT_PATH} is up to date with the models.")
        return 0

    print(f"{OUTPUT_PATH} is out of date with civic_scraper.models.")
    print("Run `uv run python checks/docs_drift.py --write` and commit the result.")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
